[roslaunch][INFO] 2025-10-11 17:12:23,693: Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2025-10-11 17:12:23,699: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2025-10-11 17:12:23,699: roslaunch starting with args ['/opt/ros/noetic/bin/roslaunch', 'launch_va50.launch']
[roslaunch][INFO] 2025-10-11 17:12:23,700: roslaunch env is environ({'ROS_VERSION': '1', 'DISABLE_ROS1_EOL_WARNINGS': '1', 'PKG_CONFIG_PATH': '/opt/pal/gallium/lib/pkgconfig:/opt/pal/gallium/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig', 'ROS_PYTHON_VERSION': '3', 'HOSTNAME': 'epan-tiago-noetic-ssh', 'VISP_WS': '/home/pal/visp-ws', 'ROS_PACKAGE_PATH': '/home/pal/ros_ws/src:/opt/pal/gallium/share:/opt/ros/noetic/share', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/pal/ros_ws/devel/share/common-lisp', 'PWD': '/home/pal/ros_ws', 'XAUTHORITY': '', 'TZ': 'Europe/Paris', 'ROS_IP': '127.0.0.1', 'HOME': '/home/pal', 'ROS_ETC_DIR': '/opt/ros/noetic/etc/ros', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'OROCOS_TARGET': 'gnulinux', 'CMAKE_PREFIX_PATH': '/home/pal/ros_ws/devel:/opt/pal/gallium:/opt/ros/noetic', 'GAZEBO_RESOURCE_PATH': '/home/pal/ros_ws/src/va50:', 'ROS_WORKSPACE': '/home/pal/ros_ws', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'PYTHONPATH': '/opt/pal/gallium/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages', 'TERM': 'xterm', 'VISP_INPUT_IMAGE_PATH': '/home/pal/visp-ws/visp-images', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'pal', 'RTT_COMPONENT_PATH': '/opt/pal/gallium/lib/orocos', 'DISPLAY': ':0', 'SHLVL': '1', 'PAL_DISTRO': 'gallium', 'ROS_MASTER_URI': 'http://127.0.0.1:11311', 'LIBGL_ALWAYS_SOFTWARE': '1', 'LD_LIBRARY_PATH': '/home/pal/ros_ws/devel/lib:/opt/pal/gallium/lib:/opt/pal/gallium/lib/x86_64-linux-gnu:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/usr/local/lib', 'GAZEBO_MODEL_PATH': '/home/pal/ros_ws/src/va50/models:', 'PATH': '/opt/pal/gallium/bin:/opt/ros/noetic/bin:/opt/pal/gallium/lib/pal_debian_utils/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LUA_PATH': ';;/opt/pal/gallium/share/lua/5.1/?.lua;/opt/pal/gallium/share/lua/5.1/?.lua', 'DEBIAN_FRONTEND': 'noninteractive', 'ROS_ROOT': '/opt/ros/noetic/share/ros', 'ROS_DISTRO': 'noetic', 'QT_X11_NO_MITSHM': '1', 'OLDPWD': '/home/pal/ros_ws', '_': '/opt/ros/noetic/bin/roslaunch', 'LC_CTYPE': 'C.UTF-8', 'ROS_LOG_FILENAME': '/home/pal/.ros/log/2ead1a4e-a6b4-11f0-8bc8-0028f8234b19/roslaunch-epan-tiago-noetic-ssh-1883.log'})
[roslaunch][INFO] 2025-10-11 17:12:23,700: starting in server mode
[roslaunch.parent][INFO] 2025-10-11 17:12:23,700: starting roslaunch parent run
[roslaunch][INFO] 2025-10-11 17:12:23,701: loading roscore config file /opt/ros/noetic/etc/ros/roscore.xml
[roslaunch][INFO] 2025-10-11 17:12:23,954: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2025-10-11 17:12:23,954: loading config file launch_va50.launch
[roslaunch][ERROR] 2025-10-11 17:12:24,027: Resource not found: The following package was not found in <arg name="world_name" value="$(find va50)/worlds/table_plate_fork_knife.world"/>: va50
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/pal/ros_ws/src
ROS path [2]=/opt/pal/gallium/share
ROS path [3]=/opt/ros/noetic/share
[roslaunch][ERROR] 2025-10-11 17:12:24,028: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2025-10-11 17:12:24,036: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 297, in _arg_tag
    value, default, doc = self.opt_attrs(tag, context, ('value', 'default', 'doc'))
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 208, in opt_attrs
    return [self.resolve_args(tag_value(tag,a), context) for a in attrs]
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 208, in <listcomp>
    return [self.resolve_args(tag_value(tag,a), context) for a in attrs]
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 189, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 392, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 405, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 164, in _find
    res = _find_executable(
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 212, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: va50
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/pal/ros_ws/src
ROS path [2]=/opt/pal/gallium/share
ROS path [3]=/opt/ros/noetic/share

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 156, in _load_config
    self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port,
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 621, in _include_tag
    self._arg_tag(t, child_ns, ros_config, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 309, in _arg_tag
    raise ResourceNotFound(
rospkg.common.ResourceNotFound: The following package was not found in <arg name="world_name" value="$(find va50)/worlds/table_plate_fork_knife.world"/>: va50
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/pal/ros_ws/src
ROS path [2]=/opt/pal/gallium/share
ROS path [3]=/opt/ros/noetic/share

[rospy.core][INFO] 2025-10-11 17:12:24,037: signal_shutdown [atexit]
